### ISSUE TITLE
Example of Enumeration

### ISSUE THREAD

**Issue by awhitford** [slick/slick#1025]
I am unclear if an Enumeration is supported?
Is there an example?

**Comment by szeiger** [comment]
It should be possible with custom type mapping (or a JdbcType implementation if you want to use a native database enumeration type) but we don't provide any convenience methods for this at the moment.

**Comment by slorber** [comment]
@szeiger thanks. Even if it's not supported out of the box it could be nice to give us some insights for this

@awhitford I've just tried the following:

```
abstract class DBEnum extends Enumeration {
  import play.api.db.slick.Config.driver.simple._
  implicit val enumMapper = MappedColumnType.base[Value,String](_.toString, this.withName)
}
```

It seems to work with Slick 2.1!

See also http://stackoverflow.com/questions/19273805/how-to-persist-enum-value-in-slick

**Comment by EdgeCaseBerg** [comment]
I've done something similar as here, but can't use the `===` in a filter against an enumeration column and am getting an error.
```
value === is not a member of slick.driver.MySQLDriver.api.Rep[MyEnumeration.Value]
```
when I use this in a filter that has multiple parts, and I'm getting an ambiguous implicit when doing a `filter` on a table with just the enum column
```
both value BooleanOptionColumnCanBeQueryCondition in object CanBeQueryCondition of type => slick.lifted.CanBeQueryCondition[slick.lifted.Rep[Option[Boolean]]]
[error]  and value BooleanCanBeQueryCondition in object CanBeQueryCondition of type => slick.lifted.CanBeQueryCondition[Boolean]
[error]  match expected type slick.lifted.CanBeQueryCondition[Nothing]
```
