### ISSUE TITLE
Table fails to compile with 3.2.0-M1

### ISSUE THREAD

**Issue by Nutomic** [slick/slick#1615]
The following code compiles and works without any problems using Slick 3.1.1:
```
  private class TestTable(tag: Tag) extends Table[(Address, time.Duration)](tag, "TEST_TABLE") {
    def address  = column[String]("address", O.PrimaryKey)
    def duration = column[Long]("duration")
    def * = (address, duration) <> [(Address, time.Duration), (String, Long)](
      tuple => (new Address(tuple._1), time.Duration.standardSeconds(tuple._2)),
      tuple => Option((tuple._1.toString, tuple._2.getStandardSeconds)))
  }
  private val testTable = TableQuery[TestTable]
```

But when using 3.2.0-M1, I get the following compilation error (using Scala 2.11.7):
```
[ant:scalac] /home/felix/workspace/ensichat/core/src/main/scala/com/nutomic/ensichat/core/util/Database.scala:83: error: wrong number of type parameters for method <>: [R](f: ((String, Long)) => R, g: R => Option[(String, Long)])(implicit evidence$2: scala.reflect.ClassTag[R])slick.lifted.MappedProjection[R,(String, Long)]
[ant:scalac]     def * = (address, duration) <> [(Address, time.Duration), (String, Long)](
[ant:scalac]             ^
```

How can I fix this code?

**Comment by cvogt** [comment]
The second type argument has moved to the implicit conversion class that enables <> to exist. so just leave it out.

`... <> [(Address, time.Duration)](...`

Does that fix it?

**Comment by cvogt** [comment]
the signature of `<>` gives it away :). `def <>[R : ClassTag](f: (U => R), g: (R => Option[U]))`

**Comment by Nutomic** [comment]
Thanks, that did it!

Here's the fixed code in case anyone has the same problem:
```


  private class TestTable(tag: Tag) extends Table[(Address, time.Duration)](tag, "TEST_TABLE") {
    def address  = column[String]("address", O.PrimaryKey)
    def duration = column[Long]("duration")
    def * = (address, duration) <> [(Address, time.Duration)](
      tuple => (new Address(tuple._1), time.Duration.standardSeconds(tuple._2)),
      tuple => Option((tuple._1.toString, tuple._2.getStandardSeconds)))
  }
  private val testTable = TableQuery[TestTable]
```
