### ISSUE TITLE
TableQuery.length broken since repQueryActionExtensionMethods was removed in 3.2.1

### ISSUE THREAD

**Issue by mellster2012** [slick/slick#1941]
When using active-slick 0.3.5 and slick  3.2.1 or higher (w/ MySqlProfile -> JdbcProfile).

EntityActions.count -> TableQuery.length -> Library.CountAll still seems trying to call repQueryActionExtensionMethods which was removed in 3.2.1

Exception in thread "ForkJoinPool-1-worker-2" java.lang.NoSuchMethodError: slick.jdbc.JdbcProfile$API.repQueryActionExtensionMethods(Lslick/lifted/Rep;)Lslick/basic/BasicActionComponent$QueryActionExtensionMethodsImpl;
	at io.strongtyped.active.slick.EntityActions.count(EntityActions.scala:30)

It works fine with 3.2.0.

**Comment by trevorsibanda** [comment]
Hi @mellster2012 can you provide more info on how to recreate this.

**Comment by hvesalai** [comment]
This seems like a binary compatibility issue. With the release of 3.3.0 I don't think we are going to fix it anymore unless somebody wants to provide the PR. 

The method in question was removed in this commit: 2b5ee55c6949d89636a1f5d9fe94d176e26b9020
