### ISSUE TITLE
What is the special configuration to enable Streaming on MySQL with 6.0.6 Driver

### ISSUE THREAD

**Issue by abhsrivastava** [slick/slick#1783]
I have already seen this thread

https://github.com/slick/slick/issues/1218

The code given in this issue does not work with the latest MySQL Driver. 

If I set the library dependency of mysql driver to 

       "mysql" % "mysql-connector-java" % "6.0.6"

Then I get the error

> [error] MyFile.scala:113: type StatementImpl is not a member of package com.mysql.jdbc
> [error]          if (statement.isWrapperFor(classOf[com.mysql.jdbc.StatementImpl])) {
> [error]                                                            ^
> [error] MyFile.scala:114: type StatementImpl is not a member of package com.mysql.jdbc
> [error]             statement.unwrap(classOf[com.mysql.jdbc.StatementImpl]).enableStreamingResults()
> [error]                                                     ^
> [error] MyFile.scala:114: value enableStreamingResults is not a member of Nothing
> [error]             statement.unwrap(classOf[com.mysql.jdbc.StatementImpl]).enableStreamingResults()
> [error]                                                                     ^
> [error] three errors found

The code in issue 1218 worked perfectly with the old mysql driver 5.1.34. but does not work with the latest.

**Comment by abhsrivastava** [comment]
I found the answer. This is the statement for the latest mysql driver.

`      def enableStream(statement: java.sql.Statement) : Unit = {
         statement match {
            case s: com.mysql.cj.jdbc.StatementImpl => s.enableStreamingResults()
            case _ =>
         }
      }
`
