### ISSUE TITLE
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast

### ISSUE THREAD

**Issue by MeerKatDev** [slick/slick#1963]
Not sure where I should post this, in case I am on the wrong forum please let me know. I just updated my project to Play 2.7.0-M4, but I can't run it because upon connection to the db, this appears:

```
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:44)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:21)
        at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:47)
        at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig(JdbcBackend.scala:287)
        at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig$(JdbcBackend.scala:284)
        at slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:32)
        at slick.jdbc.JdbcBackend.createDatabase(JdbcBackend.scala:35)
        at slick.jdbc.JdbcBackend.createDatabase$(JdbcBackend.scala:35)
        at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:516)
        at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:516)
        at slick.basic.DatabaseConfig$$anon$1.db$lzycompute(DatabaseConfig.scala:103)
        at slick.basic.DatabaseConfig$$anon$1.db(DatabaseConfig.scala:102)
        at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.$anonfun$registerDatabaseShutdownHook$3(SlickApi.scala:99)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.Try$.apply(Try.scala:209)
        at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.$anonfun$registerDatabaseShutdownHook$2(SlickApi.scala:99)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I know this method was deprecated already, and I am not sure whether this is wanted and I am doing something wrong or it is some leftover from the milestone being introduced. What version of play-hikaricp should I use with play 2.7.0-M4? I have tried 3.2.2 and 3.2.3 but the result is the same.

**Comment by MeerKatDev** [comment]
https://github.com/slick/slick/blob/42d787b4950fe876569b5fd68e98c4e0379ac83c/slick-hikaricp/src/main/scala/slick/jdbc/hikaricp/HikariCPJdbcDataSource.scala 

I suppose line 65 here should be removed?

**Comment by satendrakumar** [comment]
@MeerKatDev JDK version ??

**Comment by MeerKatDev** [comment]
```
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by ksilin** [comment]
same issue wihtout play: slick & slick-hikaricp 3.2.3, tried both HikariCP 2.7.9 & 3.2.0

**Comment by jakequist** [comment]
```scala
// build.sbt
libraryDependencies += "com.zaxxer" % "HikariCP" % "2.7.9"
```

Is a workaround that fixes it for me.

**Comment by MeerKatDev** [comment]
`
[info] play.api.Play - Application started (Dev) (no global state)
Uncaught error from thread [application-akka.actor.default-dispatcher-3]: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:44)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:21)
        at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:47)
        at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig(JdbcBackend.scala:302)
        at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig$(JdbcBackend.scala:299)
        at slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:32)
        at slick.jdbc.JdbcBackend.createDatabase(JdbcBackend.scala:35)
        at slick.jdbc.JdbcBackend.createDatabase$(JdbcBackend.scala:35)
        at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:531)
        at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:531)
        at slick.basic.DatabaseConfig$$anon$1.db$lzycompute(DatabaseConfig.scala:103)
        at slick.basic.DatabaseConfig$$anon$1.db(DatabaseConfig.scala:102)
        at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.$anonfun$registerDatabaseShutdownHook$3(SlickApi.scala:99)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.$anonfun$registerDatabaseShutdownHook$2(SlickApi.scala:99)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-3]: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:44)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:21)
        at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:47)
        at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig(JdbcBackend.scala:302)
        at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig$(JdbcBackend.scala:299)
        at slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:32)
        at slick.jdbc.JdbcBackend.createDatabase(JdbcBackend.scala:35)
        at slick.jdbc.JdbcBackend.createDatabase$(JdbcBackend.scala:35)
        at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:531)
        at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:531)
[warn] a.a.CoordinatedShutdown - Coordinated shutdown phase [service-stop] timed out after 5000 milliseconds

I just tried to compile with play-slick RC2 and play 2.7.0-RC8, this is the result upon running the application from sbt.
`

**Comment by franbulax** [comment]
I was wondering if anybody knows how to fix or work around this issue.  

It is preventing redeployment of a production application: we made some minor, unrelated changes and now the application won't run, but terminates with the following:

`Uncaught error from thread [application-akka.actor.default-dispatcher-10]: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V`

**Comment by hvesalai** [comment]
NoSuchMethodError is a problem with your jar versions. You are using libraries that are not compatible with each other. In this case it is because you are using a slick version that was compiled against some other version of hikari you are using. You cannot do that. You must use the hikari version that slick was compiled against (or at least a version that is binary compatible).

As this is not a bug in slick, I will close this issue. I invite all of you to join gitter.im and to discuss this issue on the slick channel there. And because this issue is actually a very generic one (you can get similar situations with any libraries), you can also get help from any generic java or scala channel.
